# Generated by Django 5.0.6 on 2024-05-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_categories_options_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='image_resolved',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='problems_images_resolved', verbose_name='Изображение решенной проблемы'),
        ),
    ]
