# Generated by Django 5.1.3 on 2024-11-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problems_user_alter_problems_address'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            Insert into category (name, slug) values ('Уборка территории', 'уборка территории'); 
            Insert into category (name, slug) values ('Дорожное покрытие', 'дорожное покрытие'); 
            Insert into category (name, slug) values ('Инфраструктура', 'инфраструктура'); 
            Insert into category (name, slug) values ('Благоустройство', 'благоустройство'); 
            """
        )
    ]
