# Generated by Django 5.1.3 on 2024-11-29 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_alter_problems_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='problems.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='image',
            field=models.BinaryField(blank=True, null=True, verbose_name='Изображение проблемы'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='image_resolved',
            field=models.BinaryField(blank=True, null=True, verbose_name='Изображение решенной проблемы'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название проблемы'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL'),
        ),
    ]
